### ISSUE TITLE
Highest Baud rate setting for SVL on macOS and linux fail

### ISSUE THREAD

**Issue by kirk-sfe** [sparkfun/Arduino_Apollo3#369] opened 2021-03-16 23:23 UTC
Uploading to an Artemis board on macOS or Linux using the SVL fails when the baud rate is set to 921600. Firmware upload works if the baud rate is lowered to 460800. 

**Error Message**
Target failed to enter bootload mode. Verify the right COM port is selected and that your board has the SVL bootloader.

This should be noted / tied to an issue on the SVL boot loader. 

ALSO: The error message should be fixed and not reference a "COM" port, which are non-existent on macOS/Linux.

**Comment by adamgarbo** [comment] 2021-03-24 15:18
I would also add that if the 921600 baud rate doesn't end up being supported, it would be helpful for users to either simply remove it, or change the order of the baud rates so that the Arduino IDE doesn't default automatically to 921600 when changing the selected board. This is a minor annoyance I deal with on a daily basis.

**Comment by Wenn0101** [comment] 2021-03-24 16:26
@adamgarbo If this is not fixed in the next release, we will definitely have the default changed. I agree that this is an annoyance.

**Comment by paulvha** [comment] 2021-03-29 20:55
just to add 921600 works consistent without problems on my Edge board with an FTDI Friend from Adafruit. The issue is with the CH340 chip/driver which can not handle this speed.  I have tried before CH340 board before switching and that fails constantly. 

regards,
Paul

**Comment by Wenn0101** [comment] 2022-03-17 03:16
For now the workaround seems to be sufficient. Closing this issue.

**Closed by Wenn0101** 2022-03-17 03:16 UTC

**Comment by adamgarbo** [comment] 2022-03-17 14:09
@Wenn0101 which workaround are you referring to? Having the 921600 baud rate kicked to the end of the list is a nice change (although I still use v1.2.3 where it's still at the top of the list).
